modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="realmcontrol"
version="${file.jarVersion}"
displayName="Realm Control"
authors="XYAT"
description='''
World generation, world rules, beacon area control, and teleport permission tools.
'''

[[dependencies.realmcontrol]]
modId="forge"
mandatory=true
versionRange="[47.4.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.realmcontrol]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.realmcontrol]]
modId="kineticcore"
mandatory=true
versionRange="[26.9.20,)"
ordering="AFTER"
side="BOTH"

[[dependencies.realmcontrol]]
modId="jade"
mandatory=false
versionRange="[11.0.0,)"
ordering="AFTER"
side="BOTH"
